"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "users",
      [
        {
          id: 6,
          username: "dhlEKsrlfdptj12",
          nickname: "나루터",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          username: "dhlEKsrlfdptj13",

          nickname: "미소지었다",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          username: "dhlEKsrlfdptj14",

          nickname: "demull",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          username: "dhlEKsrlfdptj15",
          nickname: "서리리링",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          username: "dhlEKsrlfdptj16",
          nickname: "라이언",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          username: "dhlEKsrlfdptj17",
          nickname: "브라이언",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          username: "dhlEKsrlfdptj18",
          nickname: "홀리몰리",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id:13,
          username: "dhlEKsrlfdptj19",
          nickname: "외딴길에서",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          username: "dhlEKsrlfdptj20",
          nickname: "마케이누세",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          username: "dhlEKsrlfdptj21",
          nickname: "피치",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          username: "dhlEKsrlfdptj22",
          nickname: "sondia",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          username: "dhlEKsrlfdptj23",
          nickname: "가로세로",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          username: "dhlEKsrlfdptj24",
          nickname: "아침에눈을뜨면",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          username: "dhlEKsrlfdptj25",
          nickname: "곰",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          username: "dhlEKsrlfdptj64",
          nickname: "곰돌이",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          username: "dhlEKsrlfdptj26",
          nickname: "smg",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          username: "dhlEKsrlfdptj24",
          nickname: "카구파",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          username: "dhlEKsrlfdptj24",
          nickname: "yone",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          username: "dhlEKsrlfdptj24",
          nickname: "on",
          password: "rlfrhrlsdugod!@3",
          salt: "sjdhkgkaRprjfdj13113wnfrptmfvma",
          email: null,
          google_id: null,
          kakao_id: null,
          social_user: false,
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("users", null, {});

    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
